### PR TITLE
Bug fix for the GitHub Organization command

### LINKED ISSUE #1135: GitHub Organization command gives undefined data if the organization doesn't exist
**Bug description**
GitHub Organization command gives undefined data if the repository doesn't exist

**How to reproduce**
1. Run `s!github organization jaheiwujhaieuwiodjaidw`
2. Observe

**Expected behavior**
Invalid organization error

**Screenshots**
image

**Additional context**
Reported by `Weariful#7333` on our Discord server (thanks!)

### PR DESCRIPTION
**Pull request by jaxxibae**
+ Fixes #1135
image

### CODE REVIEW

File: src/commands/misc/github/organization.js [hunk 1]
```diff
@@ -32,15 +31,15 @@ module.exports = class GitHubOrganization extends Command {
         .setDescription(data.description || t('commands:github.subcommands.organization.noDescription'))
         .addField(t('commands:github.subcommands.organization.members'), MiscUtils.formatNumber(orgMembers, language), true)
         .addField(t('commands:github.subcommands.organization.createdAt'), `${moment(data.created_at).format('LLL')}\n(${moment(data.created_at).fromNow()})`, true)
+
       if (data.public_repos > 0) {
         const repos = await this.client.apis.github.getOrganizationRepositories(organization)
         embed.addField(t('commands:github.subcommands.user.repositories', { count: data.public_repos }), `${repos.slice(0, 5).map(r => `\`${r.full_name}\` ${r.fork ? ` ${this.getEmoji('forked')}` : ''}`).join('\n')}${data.public_repos > 5 ? `\n${t('commands:github.subcommands.organization.moreRepos', { repos: data.public_repos - 5 })}` : ''}`, true)
       }
 
       await channel.send(embed).then(() => channel.stopTyping())
```
Comment (moruzerinho6) [inline src/commands/misc/github/organization.js]: This is not necessary. This review can be demissed if necessary.

Comment (moruzerinho6) [reply src/commands/misc/github/organization.js]: Already fixed in the last commit.

File: src/commands/misc/github/organization.js [hunk 2]
```diff
@@ -14,14 +14,13 @@ module.exports = class GitHubOrganization extends Command {
...
-    if (!await this.getOrganization(t, author, channel, language, organization)) throw new CommandError(t('commands:github.subcommands.organization.orgNotFound'))
-  }
-
-  async getOrganization (t, author, channel, language, organization) {
     try {
       channel.startTyping()
       moment.locale(language)
+
       const data = await this.client.apis.github.getOrganization(organization)
+      if (!data.login) throw new Error()
```
Comment (fernando457829) [inline src/commands/misc/github/organization.js:22]: Remove try-catch block and add error here instead throw new error on catch block.

```suggestion
      if (!data.login) throw new CommandError(t('commands:github.subcommands.organization.orgNotFound'))
```
