### PR TITLE
Weather command and some fixes

### LINKED ISSUE #77: Weather command

### PR DESCRIPTION
**Pull request by metehus**
Weather command, Google Maps API, Dark Sky API and some fixes in some js doc

Closes #77

### CODE REVIEW

**Comment by bolsomito** [comment]
rfr?

File: src/utils/CanvasTemplates.js [hunk 1]
```diff
@@ -490,4 +490,143 @@ module.exports = class CanvasTemplates {
...
+    const WIDTH = 430
+    const HEIGHT = 350
+
+    const CARD_WIDTH = 383
+    const CARD_HEIGHT = 264
+    const CARD_X_MARGIN = (WIDTH - CARD_WIDTH) * 0.5
+    const CARD_Y_MARGIN = (HEIGHT - CARD_HEIGHT) * 0.5
+
+    const FONTS = (() => {
+      const MEME = Math.random() > 0.99 && '"Comic Sans MS"'
```
Comment (pedrofracassi) [inline src/utils/CanvasTemplates.js]: I SEE YOU

File: src/apis/DarkSky.js [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+  /**
+   * Get a forecast informaitons
+   * @param {number} lat The latitude of the location (in decimal degrees)
+   * @param {number} lng The longitude of the location (in decimal degrees)
+   * @param {Object} options The request options
+   * @param {string} [options.lang=en] The language for the summary, does not apply to units
+   * @param {string} [options.units=auto] The units to the weather conditions, see more in https://darksky.net/dev/docs#forecast-request
+   * @returns {Promise<Object>} Promise with object with weather forecast info, see more in https://darksky.net/dev/docs#response-format
+   */
+  getForecast (lat, lng, options) {
```
Comment (davipatury) [inline src/apis/DarkSky.js]: If options is an optional parameter, it should be `options = { lang: 'en', units: 'auto' }`

File: src/apis/GoogleMaps.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+  searchCity (address, language = 'en-us') {
+    return new Promise(async resolve => {
+      let search = await this.request('/geocode', { address, language })
+      if (search.status === 'OK') {
+        let result = search.results[0]
+        if (!result.address_components.find(res => res.types.includes('administrative_area_level_2') || res.types.includes('locality'))) { resolve(null) }
+        resolve(result)
+      } else resolve(null)
+    })
+  }
```
Comment (davipatury) [inline src/apis/GoogleMaps.js]:
```js
async searchCity (address, language = 'en-us') {
  const { status, results: [ result ] } = await this.request('/geocode', { address, language })
  if (status === 'OK' && result.address_components.some(({ types }) => types.includes('administrative_area_level_2' || types.includes('locality')) {
    return result
  }
}```

File: src/commands/utility/weather.js [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+
+  async run ({ t, author, channel, language }, address) {
+    moment.locale(language)
+    channel.startTyping()
+    const city = await this.client.apis.gmaps.searchCity(address)
+    if (city) {
+      const cityLocation = city.geometry.location
+      const weatherData = await this.client.apis.darksky.getForecast(cityLocation.lat, cityLocation.lng, { lang: language.split('-')[0], units: 'ca' })
+      const currently = weatherData.currently
+      const daily = weatherData.daily.data
```
Comment (davipatury) [inline src/commands/utility/weather.js]: `const { currently, daily: { data: daily }, timezone } = await this.client.apis.darksky...`
(then replace [`weatherData.timezone`](https://github.com/SwitchbladeBot/switchblade/pull/498/files#diff-ec8eccb21973782ce759bff0dde79fd4R51) with just `timezone`)

File: src/commands/utility/weather.js [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+      daily.map(d => {
+        d.temperature = this.tempHumanize((d.temperatureHigh + d.temperatureLow) / 2)
+        d.icon = icons.indexOf(d.icon)
+        d.weekday = this.getTimeData(d.time, weatherData.timezone).format('ddd')
+      })
+
+      weatherInfo.daily = daily
+      const cityName = city.address_components.find(comp => comp.types.includes('administrative_area_level_2') || comp.types.includes('locality')).short_name
+      const stateName = city.address_components.find(comp => comp.types.includes('administrative_area_level_1')).short_name
```
Comment (davipatury) [inline src/commands/utility/weather.js]:
```js
const cityName = city.address_components.find(({ types }) => types.includes('administrative_area_level_2') || types.includes('locality')).short_name
const stateName = city.address_components.find(({ types }) => types.includes('administrative_area_level_1')).short_name
```

File: src/structures/command/CommandContext.js [hunk 6]
```diff
@@ -1,4 +1,21 @@
 module.exports = class CommandContext {
+  /**
+   * @param {Object} options The context options
+   * @prop {Switchblade} client The SwitchBlade client
+   * @prop {Message} message The command message
+   * @prop {User} user The author of the message
+   * @prop {GuildMember} member The author of the message as a guild member
```
Comment (davipatury) [inline src/structures/command/CommandContext.js]: `member` is nullable

File: src/structures/command/CommandContext.js [hunk 7]
```diff
@@ -1,4 +1,21 @@
 module.exports = class CommandContext {
+  /**
+   * @param {Object} options The context options
+   * @prop {Switchblade} client The SwitchBlade client
+   * @prop {Message} message The command message
+   * @prop {User} user The author of the message
+   * @prop {GuildMember} member The author of the message as a guild member
+   * @prop {TextChannel} channel The channel of the message
+   * @prop {?VoiceChannel} voiceChannel The voice channel of the author of the message, if any
+   * @prop {Guild} guild The guild of the channel of the message
```
Comment (davipatury) [inline src/structures/command/CommandContext.js]: `guild` is nullable

File: src/structures/command/CommandContext.js [hunk 8]
```diff
@@ -1,4 +1,21 @@
...
+  /**
+   * @param {Object} options The context options
+   * @prop {Switchblade} client The SwitchBlade client
+   * @prop {Message} message The command message
+   * @prop {User} user The author of the message
+   * @prop {GuildMember} member The author of the message as a guild member
+   * @prop {TextChannel} channel The channel of the message
+   * @prop {?VoiceChannel} voiceChannel The voice channel of the author of the message, if any
+   * @prop {Guild} guild The guild of the channel of the message
+   * @prop {Object} guildDocument The document of the guild
```
Comment (davipatury) [inline src/structures/command/CommandContext.js]: `guildDocument` is nullable

File: src/structures/command/CommandContext.js [hunk 9]
```diff
@@ -1,4 +1,21 @@
...
+   * @prop {string} language The language used
+   * @prop {Object} userDocument The document of the user
+   * @prop {Command} command The command
+   * @prop {?Array<string>} aliase
```
Comment (davipatury) [inline src/structures/command/CommandContext.js]: `aliase` isn't nullable and is just a `string`

File: src/utils/CanvasTemplates.js [hunk 10]
```diff
@@ -490,4 +490,143 @@ module.exports = class CanvasTemplates {
...
+      Image.buffer(Constants.WEATHER_CLEAR_NIGHT, true),
+      Image.buffer(Constants.WEATHER_CLOUDY, true),
+      Image.buffer(Constants.WEATHER_FOG, true),
+      Image.buffer(Constants.WEATHER_PARTLY_CLOUDY_DAY, true),
+      Image.buffer(Constants.WEATHER_PARTLY_CLOUDY_NIGHT, true),
+      Image.buffer(Constants.WEATHER_RAIN, true),
+      Image.buffer(Constants.WEATHER_SNOW, true),
+      Image.buffer(Constants.WEATHER_THUNDERSTORM, true),
+      Image.buffer(Constants.WEATHER_WIND, true)
+    ])
```
Comment (davipatury) [inline src/utils/CanvasTemplates.js]: I don't really like the idea of loading every single weather icon even without using some of them in the context.

File: src/utils/CanvasTemplates.js [hunk 11]
```diff
@@ -490,4 +490,143 @@ module.exports = class CanvasTemplates {
...
+
+    const MAIN_INFORMATIONS_Y = 180
+    const MAIN_INFORMATIONS_X_MARGIN = 35
+    const MAIN_INFORMATIONS_X_MARGIN_BETWEEN = 30
+
+    ctx.write(weather.now.max, CARD_X_MARGIN + MAIN_INFORMATIONS_X_MARGIN, MAIN_INFORMATIONS_Y, FONTS.INFORMATIONS, ALIGN.BOTTOM_LEFT)
+    const MAIN_INFORMATIONS_MAX_W = measureText(ctx, FONTS.INFORMATIONS, weather.now.max).width
+    ctx.write(weather.now.min, CARD_X_MARGIN + MAIN_INFORMATIONS_X_MARGIN + MAIN_INFORMATIONS_MAX_W + MAIN_INFORMATIONS_X_MARGIN_BETWEEN, MAIN_INFORMATIONS_Y, FONTS.INFORMATIONS, ALIGN.BOTTOM_LEFT)
+    const MAIN_INFORMATIONS_MIN_W = measureText(ctx, FONTS.INFORMATIONS, weather.now.min).width
+    ctx.write(weather.now.wind, CARD_X_MARGIN + MAIN_INFORMATIONS_X_MARGIN + MAIN_INFORMATIONS_MAX_W + MAIN_INFORMATIONS_MIN_W + MAIN_INFORMATIONS_X_MARGIN_BETWEEN * 2, MAIN_INFORMATIONS_Y, FONTS.INFORMATIONS, ALIGN.BOTTOM_LEFT)
```
Comment (davipatury) [inline src/utils/CanvasTemplates.js]: `ctx.write` returns some useful information, you should use it instead of using `measureText` every single time.

File: src/utils/CanvasTemplates.js [hunk 12]
```diff
@@ -490,4 +490,143 @@ module.exports = class CanvasTemplates {
...
+
+    const [ ...WEATHER_SVG_ICONS ] = await WEATHER_ICONS
```
Comment (davipatury) [inline src/utils/CanvasTemplates.js]: `const WEATHER_SVG_ICONS = await WEATHER_ICONS`

File: src/utils/CanvasTemplates.js [hunk 13]
```diff
@@ -490,4 +490,143 @@ module.exports = class CanvasTemplates {
...
+
+    const AWAIT_ICONS = Promise.all(WEATHER_SVG_ICONS.map(async icon => {
+      const canvas = await createSVGCanvas(icon.toString().replace(/\$COLOR/g, '#FFFFFF'), WEATHER_ICONS_SIZE, WEATHER_ICONS_SIZE)
+      return canvas
+    }))
```
Comment (davipatury) [inline src/utils/CanvasTemplates.js]:
```js
const AWAIT_ICONS = Promise.all(WEATHER_SVG_ICONS.map(icon => createSVGCanvas(icon.toString().replace(/\$COLOR/g, '#FFFFFF'), WEATHER_ICONS_SIZE, WEATHER_ICONS_SIZE))```

File: src/utils/CanvasTemplates.js [hunk 14]
```diff
@@ -490,4 +490,143 @@ module.exports = class CanvasTemplates {
...
+    const MAIN_ICON_RIGHT_MARGIN = 15
+    const MAIN_ICON_Y = 70
+
+    const mainTemperatureIcon = await createSVGCanvas(WEATHER_SVG_ICONS[weather.now.icon].toString().replace(/\$COLOR/g, '#FFFFFF'), MAIN_ICON_SIZE, MAIN_ICON_SIZE)
+
+    ctx.drawImage(mainTemperatureIcon, CARD_X_MARGIN + CARD_WIDTH - MAIN_ICON_RIGHT_MARGIN - MAIN_ICON_SIZE, MAIN_ICON_Y, MAIN_ICON_SIZE, MAIN_ICON_SIZE)
+
+    // WEATHER DAILY ICONS
+
+    const [ ...ICONS ] = await AWAIT_ICONS
```
Comment (davipatury) [inline src/utils/CanvasTemplates.js]: `const ICONS = await AWAIT_ICONS`

File: src/commands/utility/weather.js [hunk 15]
```diff
@@ -0,0 +1,76 @@
...
+        .setColor(Constants.ERROR_COLOR)
+        .setTitle(t('commands:weather.notFound')))
+    }
+  }
+
+  getTimeData (time, tz) {
+    let timeTz = moment.unix(time).tz(tz)
+    time = new Date(timeTz._d.valueOf() + timeTz._d.getTimezoneOffset() * 60000)
+    return moment(time)
+  }
```
Comment (davipatury) [inline src/commands/utility/weather.js]: Unnecessary, use `moment(time).tz(tz).format('ddd')` directly in the `.map`

**Comment by davipatury** [comment]
### Before rework
bfr
### After rework
aft

Most of changes were codewise.
