### PR TITLE
Command execution fixes

### LINKED ISSUE #472: If prefix is set to a special character, the bot responds to all of them.
**Bug description**
If the bot's prefix is set to a special character, for example, „.”, the bot will respond to any special character prefix, for example „"” and „ü”.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Set the bot's prefix to a special character.
2. Try to run a command with a different special character as the prefix.

**Expected behavior**
The bot should only respond to the set prefix.

**Screenshots**
screenshot_20181118091919

### LINKED ISSUE #489: Blacklist Bug Usage
**Bug description**
Appearing mode of use.

**How to reproduce**
1. Run s!blacklist

**Expected behavior**
The mode of use should not appear.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by davipatury**
- [x] Fixes #472 
- [x] Fixes #489
- [x] Removes `userDocument` and `guildDocument` from the CommandContext. These documents shouldn't be created every fucking time someone sends a message.

## CommandError
- CommandError refactor (`CommandParameters` and `CommandRequirements`)

CommandError handling in `run` function (if you throw a CommandError it'll be transformed in a embed error message). Example:
```js
if (!something) throw new CommandError(t('commands:command.noSomething'), showUsage)
```
Ps.: `showUsage` is a boolean (default false) which determines if the embed's description is going to be set to the command's usage.

### CODE REVIEW

File: src/commands/games/steamladder.js [hunk 1]
```diff
@@ -76,10 +73,8 @@ module.exports = class SteamLadder extends Command {
         .setAuthor('Steam Ladder', 'https://i.imgur.com/tm9VKhD.png')
         .setColor(embedColor)
     } catch (e) {
-      console.log(e)
-      embed = new SwitchbladeEmbed(author)
-        .setColor(Constants.ERROR_COLOR)
-        .setTitle(t('commands:steamladder.ladderNotFound'))
+      console.error(e)
```
Comment (dpaiv) [inline src/commands/games/steamladder.js]: `this.client.logError(e)` maybe?

**Comment by Doges** [comment]
still rfr right?

**Comment by davipatury** [comment]
yes
